name: AFKPrefixes
version: 1.0
api-version: 1.13
main: pw.ollie.afkprefixes.AFKPlugin

depend: [Vault]

commands:
  toggleafk:
    description: Toggles AFK

permissions:
  afkprefixes.afk:
    description: Enables usage
